/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alertas;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JToggleButton;
import ventanaPrincipal.Principal;
import ventanas.ListaDeClientes;

/**
 *
 * @author Ubaldo
 */
public class AlertaFinalizarEjecución extends javax.swing.JFrame {

    /**
     * Creates new form AlertaInicioFallidoLogin
     */
    public AlertaFinalizarEjecución() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_no = new javax.swing.JLabel();
        fondo_boton_no = new javax.swing.JButton();
        btn_si = new javax.swing.JLabel();
        fondo_boton_si = new javax.swing.JButton();
        icono_i = new javax.swing.JLabel();
        txt_pregunta = new javax.swing.JLabel();
        contenedor_02 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 80, 115));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_no.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        btn_no.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_no.setText("No");
        btn_no.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_no.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_noMouseClicked(evt);
            }
        });
        jPanel1.add(btn_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 90, 30));

        fondo_boton_no.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/Boton_aceptar.png"))); // NOI18N
        fondo_boton_no.setContentAreaFilled(false);
        fondo_boton_no.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(fondo_boton_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 90, 30));

        btn_si.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        btn_si.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_si.setText("Si");
        btn_si.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_si.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_siMouseClicked(evt);
            }
        });
        jPanel1.add(btn_si, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 90, 30));

        fondo_boton_si.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/Boton_aceptar.png"))); // NOI18N
        fondo_boton_si.setContentAreaFilled(false);
        fondo_boton_si.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(fondo_boton_si, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 90, 30));

        icono_i.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Icono_I.png"))); // NOI18N
        jPanel1.add(icono_i, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 40, 40));

        txt_pregunta.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 16)); // NOI18N
        txt_pregunta.setForeground(new java.awt.Color(255, 255, 255));
        txt_pregunta.setText("¿Desea finalizar con la ejecución?");
        txt_pregunta.setToolTipText("");
        jPanel1.add(txt_pregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, 20));

        contenedor_02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contenedores/Contenedor_02.png"))); // NOI18N
        jPanel1.add(contenedor_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 350, 165));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    JLabel txt_tiempo, txt_iniciar_pausar;
    JToggleButton btn_iniciar_pausar;
    JComboBox box_horas, box_minutos;
    JLabel txt_tiempo_agregado, txt_tiempo_total;
    private void btn_siMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_siMouseClicked
   
        ListaDeClientes cobro1 = new ListaDeClientes();
        cobro1.cobrar();
        ListaDeClientes cliente1 = new ListaDeClientes();
        cliente1.detenerYAsignarValoresDefault();
        txt_tiempo.setText("00 : 00 : 00");
        btn_iniciar_pausar.setSelected(false);
        btn_iniciar_pausar.setIcon(new ImageIcon(getClass().getResource("/botones/Boton_iniciar_pausar.png")));
        txt_iniciar_pausar.setText("Iniciar");
        box_horas.getModel().setSelectedItem("Horas");
        box_minutos.getModel().setSelectedItem("Minutos");
        txt_tiempo_agregado.setText("");
        txt_tiempo_total.setText("");
        this.dispose();
        
    }//GEN-LAST:event_btn_siMouseClicked

    public void otorgarTextoAEtiqueta(JLabel txt_tiempo, JToggleButton btn_iniciar_pausar, JLabel txt_iniciar_pausar, JComboBox box_horas, JComboBox box_minutos, JLabel txt_tiempo_agregado, JLabel txt_tiempo_total){
        this.txt_tiempo = txt_tiempo;
        this.btn_iniciar_pausar = btn_iniciar_pausar;
        this.txt_iniciar_pausar = txt_iniciar_pausar;
        this.box_horas = box_horas;
        this.box_minutos = box_minutos;
        this.txt_tiempo_agregado = txt_tiempo_agregado;
        this.txt_tiempo_total = txt_tiempo_total;
    }

    
    private void btn_noMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_noMouseClicked
        System.out.println("Aún no se requiere finalizar");
        this.dispose();
    }//GEN-LAST:event_btn_noMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlertaFinalizarEjecución.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlertaFinalizarEjecución.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlertaFinalizarEjecución.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlertaFinalizarEjecución.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlertaFinalizarEjecución().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_no;
    private javax.swing.JLabel btn_si;
    private javax.swing.JLabel contenedor_02;
    private javax.swing.JButton fondo_boton_no;
    private javax.swing.JButton fondo_boton_si;
    private javax.swing.JLabel icono_i;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txt_pregunta;
    // End of variables declaration//GEN-END:variables
}
