/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alertas;

import ventanaPrincipal.Principal;
import ventanas.IniciarSesion;

/**
 *
 * @author Ubaldo
 */
public class AlertaPreguntarSalida extends javax.swing.JFrame {

    /**
     * Creates new form AlertaInicioFallidoLogin
     */
           
   
    public AlertaPreguntarSalida() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);    
    }

    boolean salir = false;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_no = new javax.swing.JLabel();
        fondo_boton_no = new javax.swing.JButton();
        btn_si = new javax.swing.JLabel();
        fondo_boton_si = new javax.swing.JButton();
        icono_i = new javax.swing.JLabel();
        txt_pregunta = new javax.swing.JLabel();
        contenedor_02 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 80, 115));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_no.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        btn_no.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_no.setText("No");
        btn_no.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_no.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_noMouseClicked(evt);
            }
        });
        jPanel1.add(btn_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 90, 30));

        fondo_boton_no.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/Boton_aceptar.png"))); // NOI18N
        fondo_boton_no.setContentAreaFilled(false);
        fondo_boton_no.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(fondo_boton_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 90, 30));

        btn_si.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        btn_si.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_si.setText("Si");
        btn_si.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_si.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_siMouseClicked(evt);
            }
        });
        jPanel1.add(btn_si, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 90, 30));

        fondo_boton_si.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/Boton_aceptar.png"))); // NOI18N
        fondo_boton_si.setContentAreaFilled(false);
        fondo_boton_si.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(fondo_boton_si, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 90, 30));

        icono_i.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Icono_I.png"))); // NOI18N
        jPanel1.add(icono_i, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 40, 40));

        txt_pregunta.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 16)); // NOI18N
        txt_pregunta.setForeground(new java.awt.Color(255, 255, 255));
        txt_pregunta.setText("¿Realmente desea salir del sistema?");
        txt_pregunta.setToolTipText("");
        jPanel1.add(txt_pregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, 20));

        contenedor_02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contenedores/Contenedor_02.png"))); // NOI18N
        jPanel1.add(contenedor_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 350, 165));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btn_siMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_siMouseClicked
        // cerramos la ventana principal abierta
        salir = true;
        isSalir();
        
        //Cerramos esta ventana
        this.setVisible(false);
        Principal p1 = new Principal();
        
        //Abrimos la ventana iniciar sesion
        //IniciarSesion iniciarSesion1 = new IniciarSesion();
        //iniciarSesion1.setVisible(true);
        
    }//GEN-LAST:event_btn_siMouseClicked

    public boolean isSalir() {
        return salir;
    }
    
    
    
    private void btn_noMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_noMouseClicked
        this.dispose();
    }//GEN-LAST:event_btn_noMouseClicked

    public void setPrincipal(Principal a) {
        
    }

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlertaPreguntarSalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlertaPreguntarSalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlertaPreguntarSalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlertaPreguntarSalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlertaPreguntarSalida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_no;
    private javax.swing.JLabel btn_si;
    private javax.swing.JLabel contenedor_02;
    private javax.swing.JButton fondo_boton_no;
    private javax.swing.JButton fondo_boton_si;
    private javax.swing.JLabel icono_i;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txt_pregunta;
    // End of variables declaration//GEN-END:variables
}
