
package ventanas;

import alertas.AlertaInicioFallidoLogin;
import alertas.AlertaPreguntarSalida;
import conexion.Conector;
import controladores.ControladorUsuarios;
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.PasswordField;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import ventanaPrincipal.Principal;

/**
 *
 * @author Ubaldo
 */
public class IniciarSesion extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public IniciarSesion() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/iconos/Icono.png")).getImage());
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Iniciar sesión");
        campo_contrasenia.setEchoChar((char) 0);
        campo_contrasenia.setText("Ingresa tu contraseña");
        icono_mostra_ocultar_contrasenia.setEnabled(false);
        //crearArchivo();//Funcion para crear el archivo contrasenia.txt en caso que no esté

    }

    boolean selected; //En uso
    Principal principal1 = new Principal();
    AlertaInicioFallidoLogin inicioFallido1 = new AlertaInicioFallidoLogin();
    AlertaPreguntarSalida alertaPreguntarSalida1 = new AlertaPreguntarSalida();
    Perfil perfil1 = new Perfil();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_fondo = new javax.swing.JPanel();
        txt_mostrar_ocultar = new javax.swing.JLabel();
        icono_mostra_ocultar_contrasenia = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();
        Icono_user = new javax.swing.JLabel();
        txt_contrasenia1 = new javax.swing.JLabel();
        panel_boton = new javax.swing.JPanel();
        btn_iniciar_sesion = new javax.swing.JButton();
        campo_contrasenia = new javax.swing.JPasswordField();
        campo_usuario = new javax.swing.JTextField();
        txt_contrasenia = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txt_usuario = new javax.swing.JLabel();
        txt_bienvenido = new javax.swing.JLabel();
        contenedor_01 = new javax.swing.JLabel();
        titulo_sistema = new javax.swing.JLabel();
        txt_creditos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_fondo.setBackground(new java.awt.Color(239, 233, 233));
        panel_fondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_fondoMouseClicked(evt);
            }
        });
        panel_fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_mostrar_ocultar.setForeground(new java.awt.Color(153, 153, 153));
        txt_mostrar_ocultar.setText("Mostrar");
        panel_fondo.add(txt_mostrar_ocultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, -1, 20));

        icono_mostra_ocultar_contrasenia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/IconoMostrarContrasenia.png"))); // NOI18N
        icono_mostra_ocultar_contrasenia.setContentAreaFilled(false);
        icono_mostra_ocultar_contrasenia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icono_mostra_ocultar_contrasenia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icono_mostra_ocultar_contraseniaMouseClicked(evt);
            }
        });
        icono_mostra_ocultar_contrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                icono_mostra_ocultar_contraseniaActionPerformed(evt);
            }
        });
        panel_fondo.add(icono_mostra_ocultar_contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 40, 30));

        jSeparator1.setBackground(new java.awt.Color(122, 122, 122));
        panel_fondo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 230, 10));

        Icono_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/IconoUser.png"))); // NOI18N
        panel_fondo.add(Icono_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, 230, 230));

        txt_contrasenia1.setFont(new java.awt.Font("Calisto MT", 0, 20)); // NOI18N
        txt_contrasenia1.setForeground(new java.awt.Color(0, 80, 115));
        txt_contrasenia1.setText("Registrarse");
        txt_contrasenia1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt_contrasenia1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_contrasenia1MouseClicked(evt);
            }
        });
        panel_fondo.add(txt_contrasenia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 520, -1, -1));

        panel_boton.setBackground(new java.awt.Color(0, 80, 115));
        panel_boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_botonMouseEntered(evt);
            }
        });

        btn_iniciar_sesion.setBackground(new java.awt.Color(153, 153, 255));
        btn_iniciar_sesion.setFont(new java.awt.Font("Nirmala UI", 1, 22)); // NOI18N
        btn_iniciar_sesion.setForeground(new java.awt.Color(254, 254, 254));
        btn_iniciar_sesion.setText("Iniciar sesión");
        btn_iniciar_sesion.setBorderPainted(false);
        btn_iniciar_sesion.setContentAreaFilled(false);
        btn_iniciar_sesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_iniciar_sesion.setDefaultCapable(false);
        btn_iniciar_sesion.setFocusPainted(false);
        btn_iniciar_sesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_iniciar_sesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_iniciar_sesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_iniciar_sesionMouseExited(evt);
            }
        });
        btn_iniciar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciar_sesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_botonLayout = new javax.swing.GroupLayout(panel_boton);
        panel_boton.setLayout(panel_botonLayout);
        panel_botonLayout.setHorizontalGroup(
            panel_botonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_botonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_iniciar_sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_botonLayout.setVerticalGroup(
            panel_botonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_botonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_iniciar_sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel_fondo.add(panel_boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 230, 50));

        campo_contrasenia.setFont(new java.awt.Font("Gadugi", 0, 16)); // NOI18N
        campo_contrasenia.setForeground(new java.awt.Color(153, 153, 153));
        campo_contrasenia.setText("Ingresa tu contraseña");
        campo_contrasenia.setBorder(null);
        campo_contrasenia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campo_contraseniaMouseClicked(evt);
            }
        });
        campo_contrasenia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campo_contraseniaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_contraseniaKeyTyped(evt);
            }
        });
        panel_fondo.add(campo_contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 230, 40));

        campo_usuario.setFont(new java.awt.Font("Gadugi", 0, 16)); // NOI18N
        campo_usuario.setForeground(new java.awt.Color(153, 153, 153));
        campo_usuario.setText("Ingresa tu nombre de usuario");
        campo_usuario.setBorder(null);
        campo_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campo_usuarioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                campo_usuarioMouseExited(evt);
            }
        });
        campo_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_usuarioActionPerformed(evt);
            }
        });
        campo_usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campo_usuarioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_usuarioKeyTyped(evt);
            }
        });
        panel_fondo.add(campo_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 230, 40));

        txt_contrasenia.setFont(new java.awt.Font("Calisto MT", 0, 20)); // NOI18N
        txt_contrasenia.setText("Contraseña");
        panel_fondo.add(txt_contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(122, 122, 122));
        panel_fondo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 230, 10));

        txt_usuario.setFont(new java.awt.Font("Calisto MT", 0, 20)); // NOI18N
        txt_usuario.setText("Usuario");
        panel_fondo.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

        txt_bienvenido.setFont(new java.awt.Font("Nirmala UI", 1, 25)); // NOI18N
        txt_bienvenido.setText("Bienvenido");
        panel_fondo.add(txt_bienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        contenedor_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contenedores/Contenedor_01.png"))); // NOI18N
        contenedor_01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contenedor_01MouseClicked(evt);
            }
        });
        contenedor_01.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contenedor_01KeyPressed(evt);
            }
        });
        panel_fondo.add(contenedor_01, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 810, 535));

        titulo_sistema.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 36)); // NOI18N
        titulo_sistema.setText("Sistema de control clientes");
        panel_fondo.add(titulo_sistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, 67));

        txt_creditos.setForeground(new java.awt.Color(153, 153, 153));
        txt_creditos.setText("Elaborado por: Ubaldo S.J");
        panel_fondo.add(txt_creditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 700, 140, -1));

        getContentPane().add(panel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1211, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campo_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo_usuarioMouseClicked
        if (campo_usuario.getText().equals("Ingresa tu nombre de usuario")) {
            campo_usuario.setText("");
        }

        if (campo_contrasenia.getText().equals("")) {
            campo_contrasenia.setEchoChar((char) 0);
            campo_contrasenia.setText("Ingresa tu contraseña");
        }
    }//GEN-LAST:event_campo_usuarioMouseClicked

    private void campo_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_usuarioActionPerformed

    private void campo_usuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo_usuarioMouseExited

    }//GEN-LAST:event_campo_usuarioMouseExited

    private void campo_contraseniaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo_contraseniaMouseClicked

        if (campo_contrasenia.getText().equals("Ingresa tu contraseña")) {
            campo_contrasenia.setEchoChar('*');
            campo_contrasenia.setText("");
        }

        if (campo_usuario.getText().equals("")) {
            campo_usuario.setText("Ingresa tu nombre de usuario");
        }

        if (!campo_usuario.getText().equals("") && campo_contrasenia.getText().equals("")) {
            mostrarIconoContrasenia();
        }
    }//GEN-LAST:event_campo_contraseniaMouseClicked

    private void panel_botonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_botonMouseEntered

    }//GEN-LAST:event_panel_botonMouseEntered

    private void btn_iniciar_sesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_iniciar_sesionMouseEntered
        panel_boton.setBackground(new Color(0, 80, 80));
    }//GEN-LAST:event_btn_iniciar_sesionMouseEntered

    private void btn_iniciar_sesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_iniciar_sesionMouseExited
        panel_boton.setBackground(new Color(0, 80, 115));
    }//GEN-LAST:event_btn_iniciar_sesionMouseExited

    private void contenedor_01KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contenedor_01KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_contenedor_01KeyPressed

    private void contenedor_01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contenedor_01MouseClicked

        if (campo_usuario.getText().equals("")) {
            campo_usuario.setText("Ingresa tu nombre de usuario");
        }
        if (campo_contrasenia.getText().equals("")) {
            campo_contrasenia.setEchoChar((char) 0);
            campo_contrasenia.setText("Ingresa tu contraseña");
        }
    }//GEN-LAST:event_contenedor_01MouseClicked

    private void panel_fondoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_fondoMouseClicked

        if (campo_usuario.getText().equals("")) {
            campo_usuario.setText("Ingresa tu nombre de usuario");
        }
        if (campo_contrasenia.getText().equals("")) {
            campo_contrasenia.setEchoChar((char) 0);
            campo_contrasenia.setText("Ingresa tu contraseña");
        }
    }//GEN-LAST:event_panel_fondoMouseClicked

    private void campo_usuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_usuarioKeyTyped
        if (campo_usuario.getText().equals("Ingresa tu nombre de usuario")) {
            campo_usuario.setText("");
        }
    }//GEN-LAST:event_campo_usuarioKeyTyped

    private void campo_contraseniaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_contraseniaKeyTyped

        int cantidad_caracteres = campo_contrasenia.getText().length();
        if (cantidad_caracteres >= 1) {
            System.out.println("Entro aqui");
            icono_mostra_ocultar_contrasenia.setEnabled(true);
            System.out.println("Mayor o igual a 1");
            txt_mostrar_ocultar.setForeground(new Color(0, 0, 0));
        }
        if (cantidad_caracteres <= 0) {
            icono_mostra_ocultar_contrasenia.setEnabled(false);
            System.out.println("Menor o igual a 0");
            txt_mostrar_ocultar.setForeground(new Color(153, 153, 153));
        }
        if (campo_contrasenia.getText().equals("Ingresa tu contraseña")) {
            icono_mostra_ocultar_contrasenia.setEnabled(false);
            campo_contrasenia.setText("");
            txt_mostrar_ocultar.setForeground(new Color(153, 153, 153));
        }
        if (campo_contrasenia.getText().equals("")) {
            mostrarIconoContrasenia();
            txt_mostrar_ocultar.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_campo_contraseniaKeyTyped

    private void icono_mostra_ocultar_contraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_icono_mostra_ocultar_contraseniaActionPerformed
        selected = icono_mostra_ocultar_contrasenia.getModel().isSelected();
        System.out.println("Selected = " + selected);
        if (selected == true) {
            String password = new String(campo_contrasenia.getPassword());
            campo_contrasenia.setText(password);
            ocultarIconoContrasenia();
        } else {
            mostrarIconoContrasenia();
        }
    }//GEN-LAST:event_icono_mostra_ocultar_contraseniaActionPerformed

    public void mostrarIconoContrasenia() {
        icono_mostra_ocultar_contrasenia.setIcon(new ImageIcon(getClass().getResource("/iconos/IconoMostrarContrasenia.png")));
        campo_contrasenia.setEchoChar('*');
        txt_mostrar_ocultar.setText("Mostrar");
    }

    public void ocultarIconoContrasenia() {
        icono_mostra_ocultar_contrasenia.setIcon(new ImageIcon(getClass().getResource("/iconos/IconoOcultarContrasenia.png")));
        campo_contrasenia.setEchoChar((char) 0);
        txt_mostrar_ocultar.setText("Ocultar");
    }
    private void icono_mostra_ocultar_contraseniaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icono_mostra_ocultar_contraseniaMouseClicked

    }//GEN-LAST:event_icono_mostra_ocultar_contraseniaMouseClicked

    private void btn_iniciar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciar_sesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_iniciar_sesionActionPerformed

    private void txt_contrasenia1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_contrasenia1MouseClicked
        dispose();
        new Registro().setVisible(true);
    }//GEN-LAST:event_txt_contrasenia1MouseClicked

    private void btn_iniciar_sesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_iniciar_sesionMouseClicked
        String campoUsuario = campo_usuario.getText();
        String campoContrasenia = campo_contrasenia.getText();

        ControladorUsuarios controlador1 = new ControladorUsuarios();
        controlador1.iniciarSesion(campoUsuario, campoContrasenia);

        if (controlador1.isSiExiste()) {
            this.dispose();
        }

        /*
        try {
            File myFile = new File("contrasenia.txt");

            //create the scanner object
            Scanner readFile = new Scanner(myFile);

            while (readFile.hasNextLine()) {
                String contrasenia_a_comprobar = readFile.nextLine();
                System.out.println(contrasenia_a_comprobar);

                if (campo_usuario.getText().equals("admin") && campo_contrasenia.getText().equals(contrasenia_a_comprobar)) {
                    
                    this.setVisible(false);
                    dispose();
                    principal1.setVisible(true);
                    
                } else {
                    inicioFallido1.setVisible(true);
                }
            }
            readFile.close();
        } catch (FileNotFoundException x) {
            System.out.println("Un error ha ocurrido");
            x.printStackTrace();
        }
         */
    }//GEN-LAST:event_btn_iniciar_sesionMouseClicked

    private void campo_usuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_usuarioKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String campoUsuario = campo_usuario.getText();
            String campoContrasenia = campo_contrasenia.getText();

            ControladorUsuarios controlador1 = new ControladorUsuarios();
            controlador1.iniciarSesion(campoUsuario, campoContrasenia);

            if (controlador1.isSiExiste()) {
                this.setVisible(false);
                this.dispose();
            }

        }
    }//GEN-LAST:event_campo_usuarioKeyReleased

    private void campo_contraseniaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_contraseniaKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String campoUsuario = campo_usuario.getText();
            String campoContrasenia = campo_contrasenia.getText();
            ControladorUsuarios controlador1 = new ControladorUsuarios();
            controlador1.iniciarSesion(campoUsuario, campoContrasenia);
            if (controlador1.isSiExiste()) {
                this.dispose();
            }
        }
    }//GEN-LAST:event_campo_contraseniaKeyReleased

    public void crearArchivo() {

        try {
            File miArchivo = new File("contrasenia.txt");

            if (miArchivo.createNewFile()) { //Si el archivo no ha sido creado
                System.out.println("El archivo fue creado con el nombre de: " + miArchivo.getName());

                //Escribir la contraseña dentro del archivo
                try {

                    FileWriter agregarContrasenia = new FileWriter("contrasenia.txt");

                    //Agregar la contrasenia nueva a este archivo
                    agregarContrasenia.write("admin");

                    //Cerramos el archivo contrasenia.txt
                    agregarContrasenia.close();
                    System.out.println("Contrasenia agregada");
                } catch (IOException x) {
                    System.out.println("Un error ha ocurrido.");
                    x.printStackTrace();
                }

                //Leemos la contraseña dentro del archivo
                try {
                    File myFile = new File("contrasenia.txt");

                    Scanner readFile = new Scanner(myFile);
                    while (readFile.hasNextLine()) {
                        String contrasenia_a_comprobar = readFile.nextLine();
                        System.out.println("La contraseña a comprobar es: " + contrasenia_a_comprobar);

                    }
                    readFile.close();
                } catch (FileNotFoundException x) {
                    System.out.println("Un error ha ocurrido");
                    x.printStackTrace();
                }

            } else { //Si el archivo ya ha sido creado
                System.out.println("El archivo ya existe");

                //Leemos la contraseña dentro del archivo
                try {
                    File myFile = new File("contrasenia.txt");

                    Scanner readFile = new Scanner(myFile);
                    while (readFile.hasNextLine()) {
                        String contrasenia_a_comprobar = readFile.nextLine();
                        System.out.println("La contraseña a comprobar es: " + contrasenia_a_comprobar);

                    }
                    readFile.close();
                } catch (FileNotFoundException x) {
                    System.out.println("Un error ha ocurrido");
                    x.printStackTrace();
                }
            }
        } catch (IOException x) {
            System.out.println("Un error ha ocurrido");
            x.printStackTrace();
        }
    }

    public void escribirEnArchivo() {

        try {
            File myFile = new File("contrasenia.txt");

            Scanner readFile = new Scanner(myFile);
            //Leemos la contrasenia dentro del archivo contrasenia.txt
            while (readFile.hasNextLine()) {
                String contrasenia_a_comprobar = readFile.nextLine();
                System.out.println("La contraseña a comprobar es: " + contrasenia_a_comprobar);

                if (contrasenia_a_comprobar.equals("")) {//La contraseña está en blanco
                    //Si la contraseña está en blanco escribir la contrasenia
                    try {

                        FileWriter agregarContrasenia = new FileWriter("contrasenia.txt");

                        //Agregar la contrasenia nueva a este archivo
                        agregarContrasenia.write("admin");

                        //Cerramos el archivo contrasenia.txt
                        agregarContrasenia.close();
                        System.out.println("Contrasenia agregada");
                    } catch (IOException x) {
                        System.out.println("Un error ha ocurrido.");
                        x.printStackTrace();
                    }
                } else {//Si la contrasenia no está en blanco
                    //Mandar mensaje que ya hay una contraeña
                    System.out.println("Ya hay una contraseña");
                }
            }
            readFile.close();
        } catch (FileNotFoundException x) {
            System.out.println("Un error ha ocurrido");
            x.printStackTrace();
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciarSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Icono_user;
    private javax.swing.JButton btn_iniciar_sesion;
    private javax.swing.JPasswordField campo_contrasenia;
    private javax.swing.JTextField campo_usuario;
    private javax.swing.JLabel contenedor_01;
    private javax.swing.JToggleButton icono_mostra_ocultar_contrasenia;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel panel_boton;
    private javax.swing.JPanel panel_fondo;
    private javax.swing.JLabel titulo_sistema;
    private javax.swing.JLabel txt_bienvenido;
    private javax.swing.JLabel txt_contrasenia;
    private javax.swing.JLabel txt_contrasenia1;
    private javax.swing.JLabel txt_creditos;
    private javax.swing.JLabel txt_mostrar_ocultar;
    private javax.swing.JLabel txt_usuario;
    // End of variables declaration//GEN-END:variables
}
